Eatsy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from Eatsy import settings, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('authentication/', include('authentication.urls')),
    path('recipe/', include('recipe.urls')),
    path('shoppingList/', include('shoppingList.urls')),
    path('', views.principalScreen),
    path('aboutUs/', views.aboutUs),
    path('contactUs/', views.contactUs),
    path('privacyPolicy/', views.privacyPolicy),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = "Eatsy.views.errorBadRequestView"
handler403 = "Eatsy.views.errorForbiddenView"
handler405 = "Eatsy.views.errorNotAllowedView"
handler410 = "Eatsy.views.errorGoneView"
handler404 = "Eatsy.views.errorNotFoundView"
handler500 = "Eatsy.views.errorServerErrorView"

recipe/urls.py
from django.urls import path
from recipe import views

app_name = 'recipe'
urlpatterns = [
    path('show/<int:recetaId>', views.showReceta, name='show'),
    path('create', views.createReceta, name='create'),

] 

recipe/models.py
from django.db import models
from authentication.models import Perfil
from product.models import Producto

class Receta(models.Model):
    nombre = models.CharField(max_length=100, null=None)
    imagen = models.ImageField(upload_to='photos')
    descripcion = models.TextField(null=None)
    productos = models.ManyToManyField(Producto)
    perfil = models.ForeignKey(Perfil, on_delete=models.DO_NOTHING)

recipe/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from .models import Receta

class CreateRecipeForm(forms.ModelForm):
    def __init__(self, productos, *args, **kwargs):
        super(CreateRecipeForm, self).__init__(*args, **kwargs)
        self.fields['imagen'] = forms.ImageField(label="Imagen",validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], required=False, widget=forms.FileInput(attrs={'style':'display:None', 'accept':'image/*'}))
        self.fields['nombre'] = forms.CharField(label='Nombre',error_messages={'required':'Este campo no puede estar vacío'}, widget=forms.TextInput(attrs={'class' : 'form-control'}) )
        self.fields['descripcion'] = forms.CharField(label='Descripción',error_messages={'required':'Este campo no puede estar vacío'}, widget= forms.Textarea(attrs={'class' : 'form-control', 'style':'width : 100%', 'blank':'False'}))
        self.fields['productos']= forms.MultipleChoiceField(label='Selecciona un género', choices=productos, widget=forms.SelectMultiple(attrs={'class' : 'form-control', 'style':'width : 100%; height: 15em;'}))
        
   
    class Meta:
        model = Receta
        fields = ('productos', )

recipe/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from recipe.models import Receta
from django.contrib.auth.decorators import user_passes_test, login_required
from recipe.forms import CreateRecipeForm
from product.models import Producto
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from authentication.models import Perfil

def  user_active_account(user):
    if user:
        return user.perfil.activeAccount
    return False

@login_required(login_url='/authentication/login')
@user_passes_test(user_active_account, login_url='/authentication/create-subscription')
def showReceta(request, recetaId):
    receta = get_object_or_404(Receta, pk=recetaId)
    return render(request, 'recipes/show.html', {'receta': receta})

@login_required(login_url='/authentication/login')
@user_passes_test(user_active_account, login_url='/authentication/create-subscription')
def createReceta(request):
    productos = Producto.objects.filter(estado="Aceptado").order_by('titulo')
    formProducts=[]
    for product in productos:
        formProducts.append((product.id,product.titulo))
    form = CreateRecipeForm(formProducts)
    if request.method=='GET':
        return render(request,'recipes/create.html', {'form':form})
    if request.method=='POST':
        form = CreateRecipeForm(formProducts,request.POST, request.FILES)
        if form.is_valid():
            path = default_storage.save(form.cleaned_data['imagen'].name, ContentFile(form.cleaned_data['imagen'].read()))
            nombre = form.cleaned_data["nombre"]
            descripcion = form.cleaned_data["descripcion"]
            perfil = get_object_or_404(Perfil, user=request.user)
            receta = Receta(nombre=nombre, descripcion=descripcion, imagen=path, perfil=perfil)
            receta.save()
            for producto in form.cleaned_data['productos']:
                receta.productos.add(producto)
            return redirect('recipe:show', receta.pk)
        else:
            return render(request,'recipes/create.html', {'form':form})

recipe/templates/recipes/create.html
{% extends 'products/base.html' %}}
{% block titulo %}Nueva receta{% endblock %}
{% block head %}
<script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js" type="text/javascript" charset="utf-8"></script>
<script src="https://js.api.here.com/v3/3.1/mapsjs-ui.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block contenido %}
<main class="container-fluid">
    <div id="colMap" class="col-sm-7  col-10"></div>
    <h3 class="text-center mt-5 mb-3 nombreProductoGrande">Crear una nueva receta</h3>
    <div class="row justify-content-center">
        <div class="product-card-review-create col-sm-8  col-11">
            <form onsubmit="return validateImage()" name="formCreate" enctype="multipart/form-data" method="POST"
                class="post-form" action="/recipe/create">{% csrf_token %}
                <div class="form-group">
                    <label style="color:red; align-content: center;">*Solo estos campos son obligatorios.</label>
                    <br />
                    <div class="row">
                        <div class="col-md-2"><label>Imagen <span style="color:red;">*</span>:&nbsp;</label></div>
                        <label style="cursor: pointer;" class="btn btn-warning col-md-3"
                            for="id_imagen">Seleccionar archivo</label>
                        <div>{{ form.imagen }}</div>
                        <div class = "col-md-5 text-center" id="Archivo">Ninguna imagen seleccionada</div>
                        <div class="col-12" style="color: red;">{{ form.errors.imagen.as_text}}</div>
                    </div>
                    <div class="row justify-content-center">
                        <img id="foto" alt="" class="col-sm-10 col-md-8 col-lg-6">
                        <div style="color: red;">
                            {{form.imagen.errors.as_text}}
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-12"><label>Nombre <span style="color:red;">*</span>:&nbsp;</label></div>
                        <div class="col-sm-12" style="color: red;">{{ form.errors.nombre.as_text}}</div>
                        <div class="col-12">{{ form.nombre}}</div>
                        
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-sm-12"><label>Descripción <span style="color:red;">*</span>:&nbsp;</label></div>
                        <div class="col-sm-12" style="color: red;">{{ form.errors.descripcion.as_text}}</div>
                        <div class="col-sm-12">{{ form.descripcion}}</div>
                        
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-sm-12"><label>Ingredientes de la receta (Selecciona varios pulsando Ctrl): <span style="color:red;">*</span>:&nbsp;</label></div>
                        <div clas="col-sm-12" style="color: red;">{{ form.errors.productos.as_text}}</div>
                        <div class="col-sm-12">{{form.productos}}</div>
                        
                        
                    </div>
                    <br />
                    <div id="enseñaerror" class="row">

                    </div>
                    <div class="row mt-5 mb-5">
                        
                        <div class="col-auto m-auto" style="justify-content: center;">
                            <a class="btn btn-danger" onclick="mostrarAlerta()">Cancelar</a>
                            <button type="submit" class="save btn btn-warning">Guardar</button>
                        </div>
                    </div>

                    <!-- Button trigger modal -->

                
            </form>
        </div>
    </div>
</main>
<script>

    function mostrarAlerta() {
        var retVal = confirm("¿Seguro que quieres cancelar la receta?");
        if (retVal == true) {
            window.location.href = "/product/list"
            return true;
        } else {
            return false;
        }
    }
</script>

<script type="text/javascript">
    document.getElementById('id_imagen').onchange = function () {

        document.getElementById("Archivo").innerText = document.getElementById('id_imagen').files[0].name;
        previewFile();
    }
    function previewFile() {
        var preview = document.querySelector('#foto');
        var file    = document.querySelector('#id_imagen').files[0];
        var reader  = new FileReader();

        reader.onloadend = function () {
            preview.src = reader.result;
        }

        if (file) {
            reader.readAsDataURL(file);
        } else {
            preview.src = "";
        }
    }

    function validateImage() {
        var z = document.getElementById("id_imagen").files[0];
        if (!z) {
            alert("Elige una foto");
            return false;
        }  
    }
    
</script>
{% endblock %}

recipe/templates/recipes/show.html
{% extends 'products/base.html' %}{% load static %} {% block titulo %}Detalles de receta{% endblock %} {% block contenido %}

<script>
    function change_to_tab_1() {
        let pest_1 = document.getElementById("p-1");
        let pest_2 = document.getElementById("p-2");

        pest_1.style.display = "inherit";
        pest_2.style.display = "none";
    }

    function change_to_tab_2() {
        let pest_1 = document.getElementById("p-1");
        let pest_2 = document.getElementById("p-2");

        pest_1.style.display = "none";
        pest_2.style.display = "inherit";
    }
</script>
<script src="{% static 'js/rating.js' %}" defer></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="container-fluid page-content">

    <div class="row">


        <div class="col-lg-5 mb-5">
            <div id="meteHeight"></div>
            <script type="text/javascript">
            
            </script>
            <div class="product-card-inner">
                <div class="row justify-content-center">
                    <div class="col-auto mb-5 nombreProducto">Receta: {{receta.nombre}}</div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-sm-8 col-12 ">
                        <img class="product-img" style="width: 100%; max-height: 600px; border-radius: 25px;" src="{{receta.imagen.url}}" alt="">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-7">
            <div class="row justify-content-center">
                <div style="display:block;" id="menucolapsar">
                    <nav class="col-sm-4 d-flex  navbar-light">
                        <button class="navbar-toggler coll" type="button" data-toggle="collapse" data-target="#collapseproducts" aria-controls="collapseproducts" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon "></span>
                        </button>
                    </nav>
                </div>
            </div>
            <div class="row" id="collapseproducts">
                <div class="col-sm-6 d-flex botonProducto" onclick="change_to_tab_1()">
                    <span class="m-auto opProducto boton-show-inner">Descripción</span>
                </div>
                <div class="col-sm-6 d-flex botonProducto" onclick="change_to_tab_2()">
                    <span class="m-auto opProducto boton-show-inner">Ingredientes</span>

                </div>
            </div>
            <script>
                let collapseproducts = document.getElementById("collapseproducts");
                let menucolapsar = document.getElementById("menucolapsar");
                menuShow()
                let m = document.getElementById("meteHeight");
                let heightCollapse = parseInt(getComputedStyle(collapseproducts).height.replace("px", ""));
                m.style.height = (heightCollapse+16) + "px";
            

                function menuShow() {
                    if (window.innerWidth < 573) {
                        menucolapsar.style.display = "block";
                        collapseproducts.classList.add("collapse");
                    } else {
                        collapseproducts.classList.remove("collapse");
                        menucolapsar.style.display = "none"
                    }
                }
            </script>
            <div class="row">
                <hr>
            </div>
            <div class="row">
                <!-- DESCRIPCION -->
                <div class="col" id="p-1">
                    <div class="container-fluid descripcion">
                        <!-- DESCRIPCION + PRECIO -->
                        <div class="row mt-3 mb-3 product-card-descripcion">
                            <div class="row mb-2">
                                <div style="margin-left: 2%;" class="titulito">Descripción:</div>
                            </div>

                            <div class="row mb-4">
                                <div style="margin-left: 2%;">{{receta.descripcion|linebreaksbr }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- COMENTAR -->
            <div class="col" id="p-2">
                <div class="container-fluid">

                    <!-- Comentarios -->
                    {% if receta.productos %} {% for producto in receta.productos.all %}
                    {% if producto.estado == "Aceptado" %}
                    <div class="product-card-comment mb-2">
                        <div class="row titulito">
                            <div class="col-sm-12 text-center">

                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <a href="/product/show/{{producto.id}}">
                                <img style="border-radius: 20px; max-height: 120px;max-width: 120px;" src="{{producto.foto.url}}" class="col-sm-4"></img>
                            </a>
                            <div class="col-sm-4 nombreRecetaNormal col-md-6 ">
                                <div style="height: 100%; vertical-align: center; display: table; ">
                                    <div style="display: table-cell; vertical-align: middle;">
                                        <div class="text-center">
                                            <a class="enlaceRecetas " href="/product/show/{{producto.id}}">{{producto.titulo}}</a>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="row nombreRecetaMovil justify-content-center">
                                <a class="enlaceRecetas " href="/product/show/{{producto.id}}">{{producto.titulo}}</a>
                            </div>

                            <div class=" nombreRecetaNormal text-center ">
                                <div style="height: 100%; vertical-align: center; display: table; ">
                                    <div style="display: table-cell; vertical-align: middle;">
                                        <div>
                                            <a class="enlaceOjo text-center" href="/product/show/{{producto.id}}"><i class="fa fa-eye" style="font-size:44px"></a></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <br class="nombreRecetaMovil">
                            <a class="nombreRecetaMovil enlaceOjo " href="/product/show/{{producto.id}}"><i class="fa fa-eye" style="font-size:44px"></i></a> </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
</div>
</div>

<script>
    change_to_tab_1()
</script>{% endblock %}