Eatsy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from Eatsy import settings, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('authentication/', include('authentication.urls')),
    path('recipe/', include('recipe.urls')),
    path('shoppingList/', include('shoppingList.urls')),
    path('', views.principalScreen),
    path('aboutUs/', views.aboutUs),
    path('contactUs/', views.contactUs),
    path('privacyPolicy/', views.privacyPolicy),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = "Eatsy.views.errorBadRequestView"
handler403 = "Eatsy.views.errorForbiddenView"
handler405 = "Eatsy.views.errorNotAllowedView"
handler410 = "Eatsy.views.errorGoneView"
handler404 = "Eatsy.views.errorNotFoundView"
handler500 = "Eatsy.views.errorServerErrorView"

product/urls.py
from django.urls import path
from product import views

app_name = 'product'
urlpatterns = [
    path('show/<int:productId>', views.showProduct, name='show'),
    path('list', views.listProduct, name='list'),
    path('create', views.createProduct, name='create'),
    path('report/list', views.listReports, name='reportList'),
    path('review/<int:productId>', views.reviewProduct, name='review'),
    path('remove/<int:commentId>', views.removeComment, name='remove'),
    path('show/<int:productId>/rate', views.rateProduct, name='rate'),
    path('report/action/<int:reporteId>', views.reviewReport, name='review'),
    path('aboutUs/', views.aboutUs, name='aboutUs'),
    path('contactUs/', views.contactUs, name='contactUs'),
    path('privacyPolicy/', views.privacyPolicy, name='privacyPolicy'),
    path('show/shoppingList/add', views.addProductToShoppingList, name='addToShoppingList'),
] 

product/models.py
from authentication.models import Dieta, Perfil
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Ubicacion(models.Model):
    nombre = models.CharField(max_length=200, null=None)
    latitud = models.DecimalField(max_digits=9, decimal_places=6, validators=[
                                  MinValueValidator(-90), MaxValueValidator(90)],null=True)
    longitud = models.DecimalField(max_digits=9, decimal_places=6, validators=[
                                   MinValueValidator(-180), MaxValueValidator(180)],null=True)

    @property
    def esSupermercado(self):
        return int(self.latitud) == 0 and int(self.longitud) == 0

    def __str__(self):

        "Devuelve el nombre de la ubicación"
        return self.nombre

# class Dieta(models.Model):
#     nombre = models.CharField(max_length=50, null=None)

#     def __str__(self):
#         return self.nombre

class Producto(models.Model):
    State_Enum = (("Pendiente", "Pendiente de Revisión"),
                  ("Aceptado", "Aceptado"))

    titulo = models.CharField(max_length=100, null=None)
    descripcion = models.TextField(null=None)
    fecha = models.DateTimeField(auto_now=True)
    foto = models.ImageField(upload_to='photos')
    precioMedio = models.DecimalField(
        null=None,max_digits=6, decimal_places=2, validators=[MinValueValidator(0)])
    dietas = models.ManyToManyField(Dieta)
    estado = models.CharField(max_length=9, choices=State_Enum,
                              default='Pendiente', blank=False, verbose_name="Estado")
    user = models.ForeignKey(Perfil, on_delete=models.DO_NOTHING)
    ubicaciones = models.ManyToManyField(
        Ubicacion, through="UbicacionProducto")

    class Meta:
        # Por defecto se ordena por id descendiente (más nuevos primero)
        ordering = ['-id']

    def __str__(self):
        return self.titulo

class UbicacionProducto(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(Perfil, on_delete=models.DO_NOTHING)
    precio = models.DecimalField(
        null=None, max_digits=6, decimal_places=2, validators=[MinValueValidator(0)])

    def __str__(self):

        "Devuelve el nombre de la ubicación"
        return self.ubicacion.nombre

class CausaReporte(models.Model):
    causa = models.CharField(max_length=160, null=False, blank=False)

    def __str__(self):
        return self.causa

class Reporte(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    causa = CausaReporte._meta.get_field('causa')
    comentarios = models.TextField(null=False, blank=False)

    State_Enum = (("Pendiente", "Pendiente de Revisión"),
            ("Resuelto", "Resuelto"),
            ("No procede","No procede"))

    estado = models.CharField(max_length=10, choices=State_Enum,
                              default='Pendiente', blank=False, verbose_name="Estado")

    class Meta:

        "Más antiguos primero"
        ordering = ['id']

    def __str__(self):
        return '{} ({})'.format(self.producto.titulo, self.causa)

class Valoracion(models.Model):
    puntuacion = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], null=False)
    fecha = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(Perfil, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    def __str__(self):
        return self.producto.titulo + ': ' +str(self.puntuacion)

class Aportacion(models.Model):
    titulo = models.CharField(max_length=100,null=False,blank=False)
    mensaje = models.TextField(max_length=1000,null=False,blank=False)
    fecha = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(Perfil, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

product/forms.py
from enum import Enum

from authentication.models import Dieta
from django import forms
from django.core.validators import FileExtensionValidator

from .models import Aportacion, CausaReporte, Producto, Reporte, Ubicacion


class CustomMMCF(forms.ModelChoiceField):
    def label_from_instance(self, ubicacion):
        return "%s" % ubicacion.nombre

class CustomMMCF2(forms.ModelMultipleChoiceField):
    def label_from_instance(self, ubicacion):
        return "%s" % ubicacion.nombre

class CreateProductForm(forms.ModelForm):
    foto = forms.ImageField(label="Imagen",validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], required=False, widget=forms.FileInput(attrs={'style':'display:None', 'accept':'image/*'}))
    nombre = forms.CharField(label='Nombre',error_messages={'required':'Este campo no puede estar vacío'}, widget=forms.TextInput(attrs={'class' : 'form-control'}) )
    descripcion = forms.CharField(label='Descripción',error_messages={'required':'Este campo no puede estar vacío'}, widget= forms.Textarea(attrs={'class' : 'form-control', 'style':'width : 100%', 'blank':'False'}))
    precio = forms.DecimalField(label="Precio",max_digits=4, decimal_places=2, min_value=0.01, max_value=99.99, widget=forms.NumberInput(attrs={'class':'form-control'}))

    dieta = forms.ModelMultipleChoiceField(label='Etiqueta', queryset=Dieta.objects.all(), widget=forms.SelectMultiple(attrs={'class' : 'form-control', 'style':'width : 100%'}))

    ubicaciones = CustomMMCF(queryset=Ubicacion.objects.all(), required=False, widget=forms.Select(attrs={'class' : 'form-control', 'style':'width : 100%'}))
    class Meta:
        model = Ubicacion
        fields = ['nombre']

    nombreComercio = forms.CharField(label='Nombre del Comercio',strip=True, required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}) )
    lat =  forms.DecimalField(label='Latitud', widget=forms.HiddenInput, required=False )
    lon = forms.DecimalField(label='Longitud', widget=forms.HiddenInput ,required=False)



class AddUbicationForm(forms.ModelForm):
    ubicaciones = CustomMMCF(queryset= Ubicacion.objects.all().order_by("nombre"),required=False, widget=forms.Select(attrs={'class' : 'form-control'}))
    nombreComercio = forms.CharField(label='Nombre del Comercio', required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}) )
    lat =  forms.DecimalField(label='Latitud', widget=forms.HiddenInput, required=False)
    lon = forms.DecimalField(label='Longitud', widget=forms.HiddenInput ,required=False)
    precio = forms.DecimalField(label="Precio",max_digits=4, decimal_places=2, min_value=0.01, widget=forms.NumberInput(attrs={'class':'form-control'}))

    class Meta:
        model = Ubicacion
        fields = ['nombreComercio']

class ReporteForm(forms.ModelForm):
    class Meta:
        model = Reporte
        fields = ['causa', 'comentarios']
        widgets = {
            'comentarios': forms.Textarea(attrs={'class': 'form-control'})
        }

    causa = forms.ModelChoiceField(
        queryset = CausaReporte.objects.all(),
        widget = forms.RadioSelect
    )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Aportacion
        fields = ['titulo','mensaje']

    titulo= forms.CharField(label='Título', widget=forms.TextInput(attrs={'class' : 'form-control'}) )
    mensaje = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )

class SearchProductForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['titulo', 'dietas', 'ubicaciones']
        labels = {
            'titulo': 'Nombre del producto',
            'ubicaciones': 'Ubicación'
        }
        widgets = {
            'dietas': forms.CheckboxSelectMultiple(attrs={"form":"filtros-form", 'class': 'form-check'}),
            'titulo': forms.TextInput(attrs={"class":"w-100 h-100 form-control border border-dark", "placeholder":"Buscar"}),
            'ubicaciones': forms.SelectMultiple(attrs={"form":"filtros-form", "class":"w-100 h-100 form-control border border-dark"})
        }

    class OrderBy(Enum):
        newest = ('Más nuevos primero', '-id')
        oldest = ('Más antiguos primero', 'id')
        barato = ('Más baratos primero', 'precioMedio')
        caro = ('Más caros primero', '-precioMedio')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[1]
    
    orderBy = forms.TypedChoiceField(
        choices = [(orderBy.name, orderBy.value[0]) for orderBy in OrderBy],
        coerce = OrderBy.get_value,
        required = False,
        initial = OrderBy.newest.name,
        label = 'Ordenar por',
        widget = forms.Select(attrs={"form":"filtros-form", 'class': 'form-control'})
    )

    def __init__(self, *args, **kwargs):
        super(SearchProductForm, self).__init__(*args, **kwargs)
        
        self.fields['titulo'].required = False
        self.fields['dietas'].required = False
        self.fields['ubicaciones'].required = False

class ReviewProductForm(forms.ModelForm):
    foto= forms.ImageField(label="Imagen", required= False, widget=forms.FileInput(attrs={'hidden': 'True'}))
    nombre = forms.CharField(label='Nombre',error_messages={'required':'Este campo no puede estar vacío'}, widget=forms.TextInput(attrs={'class' : 'form-control'}) )
    descripcion = forms.CharField(label='Descripción',error_messages={'required':'Este campo no puede estar vacío'}, widget= forms.Textarea(attrs={'class' : 'form-control', 'style':'width : 100%'}))
    precio = forms.DecimalField(label="Precio",max_digits=4, decimal_places=2, min_value=0.01, widget=forms.NumberInput(attrs={'class':'form-control'}))

    dieta = forms.ModelMultipleChoiceField(label='Etiqueta', queryset=Dieta.objects.all(), widget=forms.SelectMultiple(attrs={'class' : 'form-control', 'style':'width : 200px'}))
    ubicaciones = CustomMMCF2(queryset= Ubicacion.objects.all(), widget=forms.SelectMultiple(attrs={'class' : 'form-control', 'style':'width : 200px'}))
    
    Revision_Enum = (
        ('Aceptar', 'Guardar'),
        ('Denegar', 'Eliminar'),
    )
    revision = forms.ChoiceField(label='Revisar', choices=Revision_Enum, widget = forms.RadioSelect)

    nombreComercio = forms.CharField(label='Nombre del Comercio', required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}) )
    lat =  forms.DecimalField(label='Latitud', widget=forms.HiddenInput, required=False)
    lon = forms.DecimalField(label='Longitud', widget=forms.HiddenInput, required=False)

    class Meta:
        model = Ubicacion
        fields = ['nombre']

class ReviewReporteForm(forms.ModelForm):
    class Meta:
        model = Reporte
        fields = ['causa', 'comentarios']
        widgets = {
            'comentarios': forms.Textarea(attrs={'class': 'form-control'})
        }
    
    causa = forms.ModelChoiceField(
        queryset = CausaReporte.objects.all(),
        widget = forms.RadioSelect
    )

    Revision_Enum = (("Resuelto", "Resuelto"),
                ("No procede","No procede"))

    revision = forms.ChoiceField(label='Revisar', choices=Revision_Enum, widget = forms.RadioSelect)

product/templates/reports/list.html
{% extends 'products/base.html' %}

{% block titulo %}Reportes{% endblock %}
{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
{% endblock %}
{% block contenido %}
<div class="row p-5 justify-content-center">
    <div class="col-md-9 col-12  ">
        <div class="row pl-3 pr-3">
            <h3><div class="col nombreProductovw">Notificaciones de productos reportados</div></h3>
        </div>
        <div class="row pl-3 pr-3">
            <div class="col-12 d-flex">
                <table class="w-100 table-responsive-md mt-3 ">
                    <tr class="border-bottom border-dark nombreProductoPeque">
                        <th>Nombre</th>
                        <th>Causa</th>
                        <th>Reportado por</th>
                        <th style="text-align: center;">Revisar producto</th>
                    </tr>
                    {% for report in reports %}
                    <tr>
                        <td class="descripcion">{{report.producto.titulo}}</td>
                        <td class="descripcion">{{report.causa}}</td>
                        <td class="descripcion">{{report.user.first_name}} {{report.user.last_name}}</td>
                        <td style="text-align: center; "><a class="enlaceOjo" data-toggle="modal"
                                data-target="#modalRep{{forloop.counter}}" role="button" aria-disabled="true" href=""><i
                                    class="fa fa-eye" style="font-size:44px"></a></i></td>

                        <div class="modal fade" id="modalRep{{forloop.counter}}" tabindex="-1" role="dialog"
                            aria-labelledby="modalRepLabel{{forloop.counter}}" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="modalRepLabel{{forloop.counter}}">Reporte
                                        </h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div style="font-weight: bold;">Producto:</div>
                                        {{report.producto.titulo}}<br><br>
                                        <div style="font-weight: bold;">Causa:</div>
                                        {{report.causa}}
                                        <br><br>
                                        <div
                                            style="font-weight: bold;">Comentarios:</div>
                                        {{report.comentarios}}

                                    </div>
                                    <div class="modal-footer justify-content-center">
                                        <a href="/product/review/{{report.producto.id}}"> <button class="btn btn-primary"
                                                style="margin-top: 0px !important;">Ver producto</button></a>
                                    </div>
                                    <div class="modal-footer justify-content-center">

                                        <form method="POST" action="/product/report/action/{{report.id}}">
                                            {% csrf_token %}
                                            <input type="hidden" name="revision" id="id_revision" value="No Procede"/>
                                            <input type="submit" class="btn col-5 btn-outline-danger"
                                                style="margin-top: 0px !important;"  value="Denegar reporte"></input>

                                        </form>
                                        <form method="POST" action="/product/report/action/{{report.id}}">
                                            {% csrf_token %}
                                            <input type="hidden" name="revision" id="id_revision" value="Resuelto"/>
                                            <input class=" btn btn-outline-success  col-5 justify-content-end" type="submit"
                                                style="margin-top: 0px !important;" value="Aprobar reporte"></input>

                                        </form>
                                        
                                    </div>
                                </div>

                            </div>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}